# cargo-deny policy enforced in CI (job "deny" in .github/workflows/ci.yml).
# FOSSA remains the license compliance product; cargo-audit covers advisories.
# Local: `make deny` or `cargo deny check`
[graph]
all-features = true

[advisories]
ignore = []

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSL-1.0",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "ISC",
    "Unicode-3.0",
    "Unlicense",
]
confidence-threshold = 0.8
exceptions = [
    { allow = ["LGPL-2.1-or-later"], crate = "r-efi" },
]

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
