//! Shared agent-packaging copy for MCP handshake and agent-rules (#2070).
//!
//! Keep strings in one place so handshake instructions and `agent-rules` cannot
//! drift on the name map, explore rule, or surface recommendations.

/// Compact CLI / plan / MCP name map (models must not invent tool ids).
pub(crate) fn canonical_name_map_markdown() -> &'static str {
    "\
## Canonical names (do not invent tool ids)\n\
\n\
| Intent | CLI | Plan op (`execute_plan`) | MCP tool |\n\
|--------|-----|--------------------------|----------|\n\
| multi-op atomic | `tx` | (plan root) | `execute_plan` |\n\
| identifier rename | `ast rename` | `ast.rename` | `ast_rename` / plan via `execute_plan` |\n\
| structured set | `doc set` / `doc update` | `doc.set` / `doc.update` | `doc_set` / plan |\n\
| search | `search` | n/a | `search_files` |\n\
| read | `read` | n/a | `read_file` |\n\
\n\
Host meta-tools (for example a host `search_tool` catalog lookup) are **not** \
patchloom MCP tools. Only list registered MCP tool names when summarizing \
patchloom usage.\n\n"
}

/// Dual-host explore rule: MCP for inspect, shell for build/test.
pub(crate) fn explore_guidance_markdown() -> &'static str {
    "\
## Explore vs shell (dual-host)\n\
\n\
When patchloom MCP is connected:\n\
\n\
- Prefer `search_files` and `read_file` (paths **relative** to MCP cwd) over \
shell `cat` / `head` / `find` / `sed` / `rg` for exploring and reading source.\n\
- Use shell only for build/test/run (`make`, `cargo test`, language runners) \
unless the user explicitly overrides.\n\
- MCP rejects absolute path strings and `../` escapes. Absolute paths from a \
host `list_dir` are not a license to pass them into patchloom tools.\n\n"
}

/// YAML / doc presentation honesty contract.
pub(crate) fn yaml_style_honesty_markdown() -> &'static str {
    "\
## Structured doc style honesty\n\
\n\
`doc.*` (CLI, plan, MCP) may re-emit **canonical YAML presentation** while \
keeping values correct (for example collapsing indented block sequences under \
a key). When presentation shifts, write JSON includes `style_changed: true`. \
Do not claim a pure surgical text edit when `style_changed` is true or when \
only the value field was intended but list indentation moved.\n\n"
}

/// Host default for coding agents (product default remains full).
pub(crate) fn core_surface_host_recommendation() -> &'static str {
    "\
## Recommended MCP surface for coding agents\n\
\n\
Product default remains **full** (compat). For coding agents (Grok, Claude, \
Cursor) with dual native tools + MCP, start with:\n\
\n\
```bash\n\
export PATCHLOOM_MCP_SURFACE=core\n\
patchloom mcp-server\n\
```\n\
\n\
Use `full` (or unset) when you need AST tools, create/delete/rename standalone \
tools, or advanced md/doc ops as first-class tools. `execute_plan` is on core \
and can still run full plan ops. See docs/plans/mcp-surface-tiers.md and \
docs/getting-started/mcp-setup.md.\n\n"
}

/// One-line recommendation for `server_info` when surface is full.
pub(crate) fn server_info_full_recommendation(tool_count: usize) -> String {
    format!(
        "Coding agents with tight context: set PATCHLOOM_MCP_SURFACE=core \
(tool_count={tool_count} on full). Product default stays full for compatibility."
    )
}

/// Short agent-rules body for `--surface core` (system-prompt injection).
pub(crate) fn agent_rules_core_body(version: &str) -> String {
    format!(
        "<!-- Generated by patchloom v{version} (surface=core) — https://github.com/patchloom/patchloom -->\n\
         # Patchloom (core pack)\n\n\
         You have MCP tools for file reads, edits, and searches. Paths are relative \
to the MCP workspace (absolute paths and `../` escapes are rejected).\n\n\
         {}\
         {}\
         {}\
         {}\
         **Core tools only** (PATCHLOOM_MCP_SURFACE=core): `read_file`, `search_files`, \
`replace_text`, `batch_replace`, `doc_get`, `doc_set`, `doc_query`, `md_replace_section`, \
`execute_plan`, `server_info`. Prefer `execute_plan` for multi-op atomic work.\n\n\
         Dry-run is the default on CLI; MCP writes apply unless the host says otherwise. \
Branch on `applied` / `error_kind`, not `ok` alone.\n",
        canonical_name_map_markdown(),
        explore_guidance_markdown(),
        yaml_style_honesty_markdown(),
        core_surface_host_recommendation(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn name_map_lists_canonical_mcp_ids() {
        let t = canonical_name_map_markdown();
        for id in [
            "execute_plan",
            "search_files",
            "read_file",
            "doc_set",
            "ast_rename",
        ] {
            assert!(t.contains(id), "missing {id}");
        }
        assert!(
            t.contains("invent") || t.contains("not** patchloom") || t.contains("Host meta-tools"),
            "name map must discourage invented ids"
        );
    }

    #[test]
    fn explore_guidance_prefers_mcp_over_shell_cat() {
        let t = explore_guidance_markdown();
        assert!(t.contains("search_files"));
        assert!(t.contains("read_file"));
        assert!(t.contains("cat"));
        assert!(t.contains("build/test") || t.contains("build"));
    }

    #[test]
    fn core_rules_are_much_shorter_than_50kb() {
        let body = agent_rules_core_body("0.0.0");
        assert!(
            body.len() < 8_000,
            "core agent-rules should stay small for system prompts, got {}",
            body.len()
        );
        assert!(body.contains("surface=core"));
    }
}
