pub mod batch;
pub mod create;
pub mod delete;
pub mod doc;
pub mod hygiene;
#[cfg(feature = "mcp")]
pub mod mcp;
pub mod md;
pub mod patch;
pub mod read;
pub mod rename;
pub mod replace;
pub mod search;
pub mod status;
pub mod tx;

use crate::cli::Cli;
use clap::{Args, Subcommand, ValueEnum};

#[derive(Debug, Subcommand)]
pub enum Command {
    /// Create a new file with specified content.
    Create(create::CreateArgs),
    /// Delete a file.
    Delete(delete::DeleteArgs),
    /// Fast literal or regex search across a repo.
    Search(search::SearchArgs),
    /// Mechanical string replacement with diff preview.
    Replace(replace::ReplaceArgs),
    /// Show which files have uncommitted changes.
    Status(status::StatusArgs),
    /// Preview or apply unified diffs safely.
    Patch(patch::PatchArgs),
    /// Read file contents with optional line range.
    Read(read::ReadArgs),
    /// Rename (move) a file.
    Rename(rename::RenameArgs),
    /// Markdown section-aware operations.
    Md(md::MdArgs),
    /// Parser-backed JSON, YAML, and TOML operations.
    Doc(doc::DocArgs),
    /// Final newline, line ending, and whitespace normalization.
    Hygiene(hygiene::HygieneArgs),
    /// Execute a multi-operation plan atomically.
    Tx(tx::TxArgs),
    /// Execute multiple operations from a simple line-oriented format.
    Batch(batch::BatchArgs),
    /// Print agent rules for using patchloom (AGENTS.md content for end users).
    AgentRules(AgentRulesArgs),
    /// Start an MCP (Model Context Protocol) server on stdio.
    #[cfg(feature = "mcp")]
    McpServer,
    /// Generate shell completions for bash, zsh, fish, or elvish.
    Completions {
        /// Shell to generate completions for.
        #[arg(value_enum)]
        shell: clap_complete::Shell,
    },
}

#[derive(Debug, Clone, Copy, ValueEnum)]
pub enum AgentMode {
    /// Include both CLI and MCP instructions (default).
    All,
    /// CLI-only: omit MCP section.
    Cli,
    /// MCP-only: omit CLI shell examples, lead with MCP tools.
    Mcp,
}

#[derive(Debug, Clone, Copy, ValueEnum)]
pub enum AgentPlatform {
    /// Include both Linux and Windows examples where they differ (default).
    All,
    /// Linux/macOS only: heredocs, single-quote shell syntax.
    Linux,
    /// Windows only: --input files, double-quote escaping.
    Windows,
}

#[derive(Debug, Args)]
pub struct AgentRulesArgs {
    /// Which integration mode to generate instructions for.
    #[arg(long, value_enum, default_value = "all")]
    pub mode: AgentMode,
    /// Which platform to generate shell examples for.
    #[arg(long, value_enum, default_value = "all")]
    pub platform: AgentPlatform,
}

fn generate_agent_rules(args: &AgentRulesArgs) -> String {
    let version = env!("CARGO_PKG_VERSION");
    let show_cli = matches!(args.mode, AgentMode::All | AgentMode::Cli);
    let show_mcp = matches!(args.mode, AgentMode::All | AgentMode::Mcp);
    let show_linux = matches!(args.platform, AgentPlatform::All | AgentPlatform::Linux);
    let show_windows = matches!(args.platform, AgentPlatform::All | AgentPlatform::Windows);

    let mut out = String::new();

    // Header
    out.push_str(&format!(
        "<!-- Generated by patchloom v{version} — https://github.com/patchloom/patchloom -->\n\
         # Patchloom\n\n"
    ));

    if show_mcp {
        out.push_str(
            "**Decision rule: if patchloom MCP tools are available (tool names starting with \
             `patchloom_`), prefer them over CLI commands.** MCP tools apply changes directly, \
             accept structured JSON, and enforce path containment.\n\n",
        );
    }
    if show_cli {
        out.push_str(
            "**Decision rule: if you are about to make 3+ tool calls for file edits, use \
             `patchloom batch` instead.** One call replaces N round-trips.\n\n",
        );
    }

    // When to use
    out.push_str(
        "Use patchloom when:\n\
         - Editing JSON, YAML, or TOML (parser-backed, preserves comments, output is always valid)\n\
         - Editing markdown sections, bullets, or tables by heading\n\
         - Batching edits across multiple files in one call\n\
         - You need atomic rollback if any edit fails\n\n\
         For single-file read, search, create, delete, or rename, your native agent tools are faster.\n\n",
    );

    // MCP section
    if show_mcp {
        out.push_str(
            "## MCP mode\n\n\
             If patchloom MCP tools are available in your session (tool names starting with \
             `patchloom_`), prefer them over CLI commands. MCP tools:\n\
             - Apply changes directly (no `--apply` flag needed)\n\
             - Accept structured JSON parameters (no shell quoting)\n\
             - Enforce path containment (cannot escape working directory)\n\n\
             Available tools: `patchloom_doc_set`, `patchloom_doc_delete`, `patchloom_doc_merge`, \
             `patchloom_doc_append`, `patchloom_doc_prepend`, `patchloom_doc_ensure`, \
             `patchloom_doc_delete_where`, `patchloom_doc_update`, `patchloom_doc_move`, \
             `patchloom_doc_get`, `patchloom_replace`, `patchloom_md_upsert_bullet`, \
             `patchloom_md_table_append`, `patchloom_md_replace_section`, `patchloom_read`, \
             `patchloom_hygiene`, `patchloom_file_rename`, `patchloom_batch`.\n\n",
        );
    }

    // Batching section
    if show_cli {
        out.push_str("## Batching (the main speed win)\n\n\
             Six file edits via native tools = six round-trips. One `batch` call = one round-trip:\n\n");

        if show_linux {
            out.push_str(
                "```bash\n\
                 patchloom batch --apply <<'EOF'\n\
                 doc.set config.json version \"2.0.0\"\n\
                 doc.set config.yaml app.version \"2.0.0\"\n\
                 replace README.md \"1.0.0\" \"2.0.0\"\n\
                 file.create hello.txt \"Hello, World!\"\n\
                 file.rename old.txt new.txt\n\
                 md.upsert_bullet CHANGELOG.md \"## Changes\" \"- Bumped to 2.0.0\"\n\
                 EOF\n\
                 ```\n\n\
                 One line per operation. Double-quote values with spaces.\n\n",
            );
        }

        if show_windows {
            if show_linux {
                out.push_str(
                    "On Windows (where heredocs are not available), write operations to a file and pass it:\n\n",
                );
            }
            out.push_str(
                "```bash\n\
                 patchloom batch --input ops.txt --apply\n\
                 ```\n\n",
            );
            if !show_linux {
                out.push_str(
                    "One line per operation in the file. Double-quote values with spaces.\n\n",
                );
            }
        }

        out.push_str(
            "For complex plans needing format/validate lifecycle, regex replace, or `--nth`, use `tx` with JSON:\n\n\
             ```bash\n\
             patchloom tx --plan plan.json --apply\n\
             ```\n\n",
        );

        // Structured edits section
        out.push_str("## Structured edits\n\n");

        if show_linux {
            out.push_str(
                "```bash\n\
                 # Edit a key in JSON/YAML/TOML (parser-backed, preserves comments)\n\
                 patchloom doc set config.json version '\"2.0.0\"' --apply\n\
                 patchloom doc merge config.yaml --value '{\"db\":{\"pool\":10}}' --apply\n\
                 \n\
                 # Append a row to a markdown table\n\
                 patchloom md table-append --file README.md --heading \"## API\" --row \"| new | row |\" --apply\n\
                 ```\n\n",
            );
        }

        if show_windows {
            if show_linux {
                out.push_str("On Windows, use double-quote escaping:\n\n");
            }
            out.push_str(
                "```bash\n\
                 patchloom doc set config.json version \"\\\"2.0.0\\\"\" --apply\n\
                 patchloom doc merge config.yaml --value \"{\\\"db\\\":{\\\"pool\\\":10}}\" --apply\n\
                 patchloom md table-append --file README.md --heading \"## API\" --row \"| new | row |\" --apply\n\
                 ```\n\n",
            );
        }

        out.push_str(
            "Add `--apply` to all write commands. Without it, patchloom previews changes without writing.\n\n",
        );
    }

    // Exit codes (always shown)
    out.push_str(
        "## Exit codes\n\n\
         | Code | Meaning |\n\
         |------|---------|\n\
         | 0 | Success (operation completed, or no changes needed) |\n\
         | 1 | Failure (error during execution) |\n\
         | 2 | Changes detected (`--check` mode found pending changes) |\n\
         | 3 | No matches (search/replace found nothing matching the pattern) |\n\
         | 4 | Parse error (malformed input file or plan) |\n\
         | 5 | Ambiguous (replacement matched multiple locations; use `--nth` to disambiguate) |\n\
         | 6 | Validation failed (tx plan validation step returned non-zero) |\n\
         | 7 | Rollback (tx apply failed partway; changes were rolled back) |\n",
    );

    out
}

pub fn dispatch(cli: Cli) -> anyhow::Result<u8> {
    let mut global = cli.global;
    match cli.command {
        #[cfg(feature = "mcp")]
        Command::McpServer => mcp::run_mcp_server(),
        Command::AgentRules(args) => {
            let output = generate_agent_rules(&args);
            print!("{output}");
            Ok(crate::exit::SUCCESS)
        }
        Command::Completions { shell } => {
            let mut cmd = <Cli as clap::CommandFactory>::command();
            clap_complete::generate(shell, &mut cmd, "patchloom", &mut std::io::stdout());
            Ok(crate::exit::SUCCESS)
        }
        Command::Read(args) => read::run(args, &global),
        Command::Search(args) => search::run(args, &global),
        Command::Status(args) => status::run(args, &global),
        Command::Create(args) => {
            global.merge_write(&args.write);
            create::run(args, &global)
        }
        Command::Delete(args) => {
            global.merge_write(&args.write);
            delete::run(args, &global)
        }
        Command::Rename(args) => {
            global.merge_write(&args.write);
            rename::run(args, &global)
        }
        Command::Replace(args) => {
            global.merge_write(&args.write);
            replace::run(args, &global)
        }
        Command::Patch(args) => {
            global.merge_write(&args.write);
            patch::run(args, &global)
        }
        Command::Md(args) => {
            global.merge_write(&args.write);
            md::run(args, &global)
        }
        Command::Doc(args) => {
            global.merge_write(&args.write);
            doc::run(args, &global)
        }
        Command::Hygiene(args) => {
            global.merge_write(&args.write);
            hygiene::run(args, &global)
        }
        Command::Tx(args) => {
            global.merge_write(&args.write);
            tx::run(args, &global)
        }
        Command::Batch(args) => {
            global.merge_write(&args.write);
            batch::run(args, &global)
        }
    }
}
